server:
  connection-timeout: 2000
  port: 80

spring:
  datasource:
    url: jdbc:mysql://10.138.228.199:33806/dps?useSSL=false
    username: root
    password: dps@2019
  redis:
    host: 10.138.228.199
    port: 32626
    password: 5IkiyQj@iT

dps:
  gitlabUrl: http://10.138.8.34
  gitlabAccessToken: KBzjBvYVpgzUzzCApXjx

